spring:
  application:
    name: itdj-upms-server
  profiles:
    active: dev
  cloud:
    config:
      fail-fast: true
      discovery:
        service-id: cloud-config-server
        enabled: true
      profile: ${spring.profiles.active}
      label: ${spring.profiles.active}

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://itcast:itcast123@127.0.0.1:8761/eureka/
#        - http://itcast:itcast123@127.0.0.1:8762/eureka/
    registry-fetch-interval-seconds: 10
