eureka:
  client:
    serviceUrl:
      defaultZone: http://itcast:itcast123@127.0.0.1:8761/eureka/,http://itcast:itcast123@127.0.0.1:8762/eureka/
server:
  port: 8769
spring:
  application:
    name: cloud-zuul
zuul:
  routes:
    feign-consumer: /api-a/**
    cloud-client-order: /api-b/**
